language: cpp
dist: bionic
os: linux

compiler:
  - gcc
  - clang

env:
  global:
    - CACHE_DIR=~/cached-deps
    - YCM_CHECKOUT=ycm-0.11
  matrix:
    - YARP_CHECKOUT=yarp-3.3
    - YARP_CHECKOUT=yarp-3.2

matrix:
  include:
    - if: type = cron
      compiler: gcc
      env: ROBOTOLOGY_CHECKOUT=master
    - if: type = cron
      compiler: clang
      env: ROBOTOLOGY_CHECKOUT=master

cache:
  directories: $CACHE_DIR

addons:
  apt:
    packages:
    # YARP
    - libeigen3-dev

    # OpenRAVE
    - libboost-all-dev
    - libqt4-dev
    - qt4-dev-tools
    - libxml2-dev
    - libode-dev
    - libsoqt4-dev
    - libcoin80-dev
    - rapidjson-dev

    # code coverage
    - lcov

before_install:
  #-- Code coverage
  - if [ "$CXX" = "g++" ]; then gem install coveralls-lcov; fi

install:
  #-- Install YCM
  - >
    source "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name YCM
    --repo-url https://github.com/robotology/ycm
    --repo-checkout "${ROBOTOLOGY_CHECKOUT:-$YCM_CHECKOUT}"

  #-- Install YARP
  - >
    source "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name YARP
    --repo-url https://github.com/robotology/yarp
    --repo-checkout "${ROBOTOLOGY_CHECKOUT:-$YARP_CHECKOUT}"
    --additional-cmake-options "-DSKIP_ACE:BOOL=ON"
    --prepend-to-linker-path lib
    --additional-export-paths "YARP_DATA_DIRS;share/yarp"

  #-- Install OpenRAVE
  - >
    source "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name OpenRAVE
    --repo-url https://github.com/rdiankov/openrave
    --repo-checkout master
    --additional-cmake-options "-DOPT_VIDEORECORDING:BOOL=OFF -DOPT_IKFAST_FLOAT32:BOOL=OFF"
    --prepend-to-linker-path lib
    --cmake-env 'CFLAGS="-w" CXXFLAGS="-w"'

  #-- Install color-debug
  - >
    source "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name COLOR_DEBUG
    --repo-url https://github.com/roboticslab-uc3m/color-debug
    --repo-checkout develop

  #-- Install asrob-uc3m/yarp-devices (for YarpOpenraveRobotManager)
  - >
    source "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name ASROB_YARP_DEVICES
    --repo-url https://github.com/asrob-uc3m/yarp-devices
    --repo-checkout develop
    --additional-export-paths "YARP_DATA_DIRS;share/asrob-yarp-devices"

  #-- Install kinematics-dynamics (for robotDraw example)
  - >
    source "$TRAVIS_BUILD_DIR/scripts/travis/git-cache-dependency.sh"
    --package-name ROBOTICSLAB_KINEMATICS_DYNAMICS
    --repo-url https://github.com/roboticslab-uc3m/kinematics-dynamics
    --repo-checkout develop
    --additional-export-paths "YARP_DATA_DIRS;share/roboticslab-kinematics-dynamics"

before_script:
  - mkdir -p "$TRAVIS_BUILD_DIR/build" && cd "$_"
  - cmake .. -DCMAKE_INSTALL_PREFIX="$PWD/install" -DENABLE_coverage:BOOL=ON
  - make install

  - export LD_LIBRARY_PATH=$PWD/install/lib:$LD_LIBRARY_PATH
  - export YARP_DATA_DIRS=$PWD/install/share/roboticslab-openrave-yarp-plugins:$YARP_DATA_DIRS
  - export CMAKE_PREFIX_PATH="$PWD/install/lib/cmake/ROBOTICSLAB_OPERNAVE_YARP_PLUGINS:$CMAKE_PREFIX_PATH"

  - mkdir -p "$TRAVIS_BUILD_DIR/build/robotDraw" && cd "$_"
  - cmake "$TRAVIS_BUILD_DIR/examples/cpp/robotDraw" && make

script:
  - echo "No unit tests available"

after_success:
  #-- Code coverage
  - if [ "$CXX" = "g++" ]; then source "$TRAVIS_BUILD_DIR/scripts/travis/coverage.sh"; fi

  - cd "$TRAVIS_BUILD_DIR/build" && make uninstall
